---
dependencies:
  - role: kubernetes-apps/persistent_volumes/openstack
    when:
      - cloud_provider is defined
      - cloud_provider in [ 'openstack' ]
    tags:
      - persistent_volumes_openstack

  - role: kubernetes-apps/persistent_volumes/cinder-csi
    when:
      - cinder_csi_enabled
    tags:
      - persistent_volumes_cinder_csi
      - cinder-csi-driver

  - role: kubernetes-apps/persistent_volumes/aws-ebs-csi
    when:
      - aws_ebs_csi_enabled
    tags:
      - persistent_volumes_aws_ebs_csi
      - aws-ebs-csi-driver
